apiVersion: v1
kind: Service
metadata:
  name: 3-column-preview-card-component
  namespace: default
spec:
  selector:
    app: 3-column-preview-card-component-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
